import pyttsx3
engine = pyttsx3.init()
print("Welcome To Railway Reservsation")
engine.say("welcome to railway resevation")
engine.runAndWait()

a=0
d=0
while(a!=101 and a!=102 and a!=103 and a!=104 and a!=105):
     engine.say("enter the station number")
     engine.runAndWait()
     a=int(input("Enter station number:"))
     if(a==101):
          engine.say("enter the number of passengers")
          engine.runAndWait()
          b=int(input("Enter the number of passengers:"))
          engine.say("your destination is chennai to namakkal")
          engine.runAndWait()
          print("Chennai to Namakkal")
          c=b*400
          engine.say("your ticket price for chennai to namakkal is",c)
          engine.runAndWait()
          print("Your ticket price for Chennai to Namakkal is ",c)
     elif(a==102):
          engine.say("enter the number of passengers")
          engine.runAndWait()
          b=int(input("Enter the number of passengers:"))
          engine.say("your destination is chennai to salem")
          engine.runAndWait()
          print("Chennai to Salem")
          c=b*350
          engine.say("your ticket price for chennai to salem is",c)
          engine.runAndWait()
          print("Your ticket price for Chennai to Salem is ",c)
     elif(a==103):
          engine.say("enter the number of passengers")
          engine.runAndWait()
          b=int(input("Enter the number of passengers:"))
          engine.say("your destination is chennai to aathur")
          engine.runAndWait()
          print("Chennai to Aatur")
          c=b*300
          engine.say("your ticket price for chennai to aathur is",c)
          engine.runAndWait()
          print("Your ticket price for Chennai to Aatur is ",c)
     elif(a==104):
          engine.say("enter the number of passengers")
          engine.runAndWait()
          b=int(input("Enter the number of passengers:"))
          engine.say("your destination is chennai to chinna salem ")
          engine.runAndWait()
          print("Chennai to Chinna salem ")
          c=b*250
          engine.say("your ticket price for chennai to chinna salem is",c)
          engine.runAndWait()
          print("Your ticket price for Chennai to chinna salem  is ",c)
     elif(a==105):
          engine.say("enter the number of passengers")
          engine.runAndWait()
          b=int(input("Enter the number of passengers:"))
          engine.say("your destination is chennai to villupuram ")
          engine.runAndWait()
          print("Chennai to Villupuram")
          c=b*200
          engine.say("your ticket price for chennai to Villupuram is",c)
          engine.runAndWait()
          print("Your ticket price for Chennai to Villupuram is ",c)
     else:
         print("Enter the valid")
         engine.say("please enter the valid")
         engine.runAndWait()
         engine.say("please")
         engine.runAndWait()
engine.say("enter the mode of payment")
engine.runAndWait()
engine.say("1=debit card")
engine.runAndWait()
print("1=Debit card")
engine.say("2=credit card")
engine.runAndWait()
print("2=Credit card")
engine.say("3=net banking")
engine.runAndWait()
print("3=Net Banking")
engine.say("4=paying at station")
engine.runAndWait()
print("4=Paying at satation")
while(d!=4):
     engine.say("Enter the mode of payment")
     engine.runAndWait()
     d=int(input("Enter the mode of payment:"))
     if(d==1):
         print("Debit Card")
         engine.say("Currently debit card service is not Available")
         engine.runAndWait()
         print("Currently Debit card service is not Available")
         engine.say("please")
         engine.runAndWait()
     elif(d==2):
         print("Credit Card")
         engine.say("Currently credit card service is not Available")
         engine.runAndWait()
         print("Currently Credit card service is not Available")
         engine.say("please")
         engine.runAndWait()
     elif(d==3):
         print("Net Banking")
         engine.say("Currently Net Banking service is not Available")
         engine.runAndWait()
         print("Currently service is not Available")
         engine.say("please")
         engine.runAndWait()
     elif(d==4):
         print("pay at station")
         engine.say("pay the amount. at sation. before three hours. for your travel")
         engine.runAndWait()
         print("Pay the amount at sation before three hours for your Travel")
         engine.say("your seats has been confirmed")
         engine.runAndWait()
         print("Your seats has been confirmed")
     else:
         print("Enter the valid")
         engine.say("please enter the valid")
         engine.runAndWait()
         engine.say("please")
         engine.runAndWait()
print("Please Share your Feedback")
engine.say("Please Share your Feedback")
engine.runAndWait()
engine.say("1=Poor")
engine.runAndWait()
print("1=Poor")
engine.say("2=Need improvement")
engine.runAndWait()
print("2=Need improvement")
engine.say("3=Good")
engine.runAndWait()
print("3=Good")
engine.say("4=Very good")
engine.runAndWait()
print("4=Very good")
engine.say("5=Excellent")
engine.runAndWait()
print("5=Excellent")
engine.say("Enter your Rating")
engine.runAndWait()
m=int(input("Enter your Rating:"))
if(m==1 or m==2):
     print("Thank you for your feedback we Enhancing our platform")
     engine.say("Thank you for your feedback we Enhancing our platform")
     engine.runAndWait()
     engine.say("Thank you for contacting us. happy ya nice day")
     engine.runAndWait()
elif(m==3 or m==4 or m==5):
     print("Thank you for your feedback")
     engine.say("Thank you for your feedback")
     engine.runAndWait()
     engine.say("Thank you for contacting us. happy ya nice day")
     engine.runAndWait()
else:
     engine.say("Thank you for contacting us. happy ya nice day")
     engine.runAndWait()
